/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.*;
import java.awt.geom.Point2D;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Random;
import javax.swing.*;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author user
 */
public class costumask extends javax.swing.JFrame {

    /**
     * Creates new form costumask
     */
    public costumask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("number of players :");

        jButton1.setText("confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30s", "60s", "90s" , "120s", "no limit" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("time :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 player", "3 player", "4 player", "5 player" }));
        jComboBox2.setSelectedIndex(2);
        jComboBox2.setToolTipText("");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setText("number of country : ");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12", "13", "14", "15", "16", "17" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel4.setText("color :");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pink", "Orange", "Yellow", "Lime", "Cyan", "Blue", "BlueViolet", "Magenta", "HotPink", "Green", "Purple", "Tomato", "DarkTurquoise", "Crimson", "Teal", "OrangeRed", "Indigo", "DarkRed", "Maroon", "DimGray" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)
                                                        .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

        int color = jComboBox5.getSelectedIndex();
        User.color = color;
        // TODO add your handling code here:
        int countryNumber = 9;



        int indexPlayerOne = 3;
        Color player1Color = new Color(Colors.colorArrayList.get(0)[0] , Colors.colorArrayList.get(0)[1], Colors.colorArrayList.get(0)[2]);


//        Color partitionColor = new Color(colorArrayList.get(i)[0], colorArrayList.get(i)[1], colorArrayList.get(i)[2]);




        // numCountry = 11;
        SwingUtilities.invokeLater(() -> {
            int remainingTimee = (jComboBox1.getSelectedIndex()+1)*30 ;
            if(jComboBox1.getSelectedIndex() == 4){
                remainingTimee = 3600;
            }

            int numCountry = jComboBox3.getSelectedIndex() + 10;
            int numPlayer = jComboBox2.getSelectedIndex()+2;
//            JFrame frame = new JFrame("Voronoi Diagram Map Generator");

            System.out.println("numberCountry: " + numCountry);
            NewV mapGenerator = new NewV(numPlayer, false , remainingTimee , numCountry);
            mapGenerator.frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            mapGenerator.initCountry = false;
            mapGenerator.initGame = false;
            System.out.println(numCountry);
//             mapGenerator.NUM_PARTITIONS = 10;
            mapGenerator.setPreferredSize(new Dimension(mapGenerator.PANEL_WIDTH, mapGenerator.PANEL_HEIGHT));
            int u = 0;

            for(int i = 0; i < mapGenerator.countAttackCountry; i++){
                u++;
                new AttackerCountry();
                int countryId = Country.countryList.size() - 1;
                mapGenerator.partitions.get(countryId).setPartitionIcon("attack.png");

            }
            for(int i = 0; i <  mapGenerator.countArcherCountry; i++){
                u++;
//                Color color = mapGenerator.partitions.get(i).getColor();
                new ArcherCountry();
                int countryId = Country.countryList.size() - 1;
                mapGenerator.partitions.get(countryId).setPartitionIcon("bow1.png");
            }
            for(int i = 0; i <  mapGenerator.countMuinusSelf; i++){
                u++;
//                Color color = mapGenerator.partitions.get(i).getColor();
                new MinusSelfCountry();
                int countryId = Country.countryList.size() - 1;
                mapGenerator.partitions.get(countryId).setPartitionIcon("pirate.png");
            }

            for(int i = 0; i < mapGenerator.NUM_PARTITIONS - mapGenerator.countAttackCountry - mapGenerator.countArcherCountry - mapGenerator.countMuinusSelf; i++){
//                Color color = mapGenerator.partitions.get(i).getColor();
                new NormalCountry();
                u++;
                int countryId = Country.countryList.size() - 1;
                mapGenerator.partitions.get(countryId).setPartitionIcon("simple.png");
            }

            System.out.println("u: " + u);
            System.out.println("size: " + Country.countryList.size());
            System.out.println("size2: " + mapGenerator.partitions.size());

//            mapGenerator.initCountry = true;

            Player player1;
            if(mapGenerator.isRandom) {
                player1 = new Player(0 , mapGenerator.getPlayerCountry() , mapGenerator.partitions.get(mapGenerator.getPlayerCountry()).getColor() , 30);
                mapGenerator.player1 = player1;
            }

            // else player1 = new Player(0 , mapGenerator.playerCountryId.get(0) , mapGenerator.partitions.get(mapGenerator.playerCountryId.get(0)).getColor() , 30);

            int countPlayer = mapGenerator.countPlayer;
//            Country.countryList.get(indexPlayerOne).setCathcerId(player1.getId());
            for(int i = 1; i < countPlayer; i++){
//            Color playerColor = new Color(Colors.colorArrayList.get(0)[0] , Colors.colorArrayList.get(0)[1], Colors.colorArrayList.get(0)[2]);

//                int randomNumber = (int) Math.floor(Math.random() *(Country.countryList.size() - 0 + 1) + 0);
//                for (Partition partition : mapGenerator.partitions) {
//
//                }
                if(mapGenerator.isRandom)  new Player(i , i , mapGenerator.partitions.get(i).getColor() , 30);
                // else new Player(i , mapGenerator.playerCountryId.get(i) , mapGenerator.partitions.get( mapGenerator.playerCountryId.get(i)).getColor() , 30);


            }



            if(mapGenerator.isRandom) mapGenerator.initGame = true;

            if(mapGenerator.isRandom) mapGenerator.startAi();
            mapGenerator.initCountry = true;

            for (int i = 0; i < Country.countryList.size(); i++){
                System.out.println(Country.countryList.get(i).getCathcerId());
            }


            mapGenerator.frame.setContentPane(mapGenerator);
            mapGenerator.frame.setSize(1400, 800);
            mapGenerator.frame.setLocationRelativeTo(null);
            mapGenerator.frame.setVisible(true);
        });
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(costumask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(costumask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(costumask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(costumask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new costumask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
