/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
// package javaapplication10;
import java.awt.event.*;
import java.awt.geom.Point2D;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Random;
import javax.swing.*;
import java.awt.Color;
import java.awt.Dimension;


import static java.lang.Math.abs;
/**
 *
 * @author user
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("random");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("costum");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("online");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        int countryNumber = 9;



        int indexPlayerOne = 3;
        Color player1Color = new Color(Colors.colorArrayList.get(0)[0] , Colors.colorArrayList.get(0)[1], Colors.colorArrayList.get(0)[2]);


//        Color partitionColor = new Color(colorArrayList.get(i)[0], colorArrayList.get(i)[1], colorArrayList.get(i)[2]);



        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Voronoi Diagram Map Generator");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            NewV mapGenerator = new NewV(3 , true , 150 , 18);

            mapGenerator.setPreferredSize(new Dimension(mapGenerator.PANEL_WIDTH, mapGenerator.PANEL_HEIGHT));

            for(int i = 0; i < mapGenerator.countAttackCountry; i++){
                new AttackerCountry();
                int countryId = Country.countryList.size() - 1;
                mapGenerator.partitions.get(countryId).setPartitionIcon("attack.png");

            }
            for(int i = 0; i <  mapGenerator.countArcherCountry; i++){
//                Color color = mapGenerator.partitions.get(i).getColor();
                new ArcherCountry();
                int countryId = Country.countryList.size() - 1;
                mapGenerator.partitions.get(countryId).setPartitionIcon("bow1.png");
            }
            for(int i = 0; i <  mapGenerator.countMuinusSelf; i++){
//                Color color = mapGenerator.partitions.get(i).getColor();
                new MinusSelfCountry();
                int countryId = Country.countryList.size() - 1;
                mapGenerator.partitions.get(countryId).setPartitionIcon("pirate.png");
            }

            for(int i = 0; i < mapGenerator.NUM_PARTITIONS - mapGenerator.countAttackCountry - mapGenerator.countArcherCountry - mapGenerator.countMuinusSelf; i++){
//                Color color = mapGenerator.partitions.get(i).getColor();
                new NormalCountry();
                int countryId = Country.countryList.size() - 1;
                mapGenerator.partitions.get(countryId).setPartitionIcon("simple.png");
            }
            Player player1;
            if(mapGenerator.isRandom) {
                player1 = new Player(0 , mapGenerator.getPlayerCountry() , mapGenerator.partitions.get(mapGenerator.getPlayerCountry()).getColor() , 30);
                mapGenerator.player1 = player1;
            }
            // else player1 = new Player(0 , mapGenerator.playerCountryId.get(0) , mapGenerator.partitions.get(mapGenerator.playerCountryId.get(0)).getColor() , 30);

            int countPlayer = mapGenerator.countPlayer;
//            Country.countryList.get(indexPlayerOne).setCathcerId(player1.getId());
            for(int i = 1; i < countPlayer; i++){
//            Color playerColor = new Color(Colors.colorArrayList.get(0)[0] , Colors.colorArrayList.get(0)[1], Colors.colorArrayList.get(0)[2]);

//                int randomNumber = (int) Math.floor(Math.random() *(Country.countryList.size() - 0 + 1) + 0);
//                for (Partition partition : mapGenerator.partitions) {
//
//                }
                if(mapGenerator.isRandom)  new Player(i , i , mapGenerator.partitions.get(i).getColor() , 30);
                // else new Player(i , mapGenerator.playerCountryId.get(i) , mapGenerator.partitions.get( mapGenerator.playerCountryId.get(i)).getColor() , 30);


            }

            if(mapGenerator.isRandom) mapGenerator.startAi();
            mapGenerator.initCountry = true;

            for (int i = 0; i < Country.countryList.size(); i++){
                System.out.println(Country.countryList.get(i).getCathcerId());
            }


            frame.setContentPane(mapGenerator);
            frame.setSize(1400, 800);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        costumask cos = new costumask();
        this.setVisible(false);
        cos.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
